root:
  startup:
    session_name: "test"
    environment: "local"

  repositories:
    #options: memory, sql
    factory_type: "memory"

  token_auth:
    #options: none, jwt
    factory_type: "jwt"
    #minutos
    expiration: 5
    jwt_key: "1qazxsw23edcvfr45tgbnhy6"

  authentication:
    #options: none, database
    factory_type: "none"

  databases:
    #list of repositories. The childs of this elements are the session names.
    test:
      type: "none"
    local:
      type: "sql"
      connection_string: ""
    production:
      type: "sql"
      connection_string: ""


