root:
  startup:
    session_name: "test"
    environment: "local"

  repositories:
    #options: memory, sql
    factory_type: "sql"

  token_auth:
    #options: none, jwt
    factory_type: "jwt"
    #minutos
    expiration: 5
    jwt_key: "1qazxsw23edcvfr45tgbnhy6"

  authentication:
    #options: none, database
    factory_type: "database"
    #options: plain, hash
    password: "hash"

  databases:
    #list of repositories. The childs of this elements are the session names.
    test:
      type: "sql"
      driver: "sqlite3"
      datasource: "./dbs/test.db3"

    production:
      type: "sql"
      driver: "sqlite3"
      datasource: "./dbs/production.db3"


